CREATE TABLE SharedArticles (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    Title NVARCHAR(255),
    Content NVARCHAR(MAX),
    Tag NVARCHAR(100),
    SharedAt DATETIME
);
CREATE TABLE SystemLog (
    LogID INT IDENTITY(1,1) PRIMARY KEY,
    Timestamp DATETIME NOT NULL DEFAULT GETDATE(),
    LogLevel NVARCHAR(50),
    Message NVARCHAR(MAX),
    Details NVARCHAR(MAX)
);
