CREATE TABLE SharedArticles (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    Title NVARCHAR(255),
    Content NVARCHAR(MAX),
    Tag NVARCHAR(100),
    SharedAt DATETIME
);
CREATE TABLE SystemLog (
    LogID INT IDENTITY(1,1) PRIMARY KEY,
    Timestamp DATETIME NOT NULL DEFAULT GETDATE(),
    LogLevel NVARCHAR(50),
    Message NVARCHAR(MAX),
    Details NVARCHAR(MAX)
);
CREATE TABLE UserTags (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    Tag NVARCHAR(100)
);
CREATE TABLE Notifications (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    Message NVARCHAR(MAX),
    CreatedAt DATETIME DEFAULT GETDATE(),
    IsRead BIT DEFAULT 0
);
CREATE TABLE Reports (
    ReportID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    ArticleID INT NOT NULL,
    Reason NVARCHAR(MAX),
    ReportedAt DATETIME NOT NULL
);
CREATE TABLE BlockedUsers (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    BlockerID INT NOT NULL,
    BlockedID INT NOT NULL,
    BlockedAt DATETIME DEFAULT GETDATE()
);

